version: '3.8'

name: siagro
services:
    nextjs:
        container_name: siagro-next-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8888:3000'
        environment:
            - NODE_ENV=production
